# Generated by Django 3.2.4 on 2021-06-09 08:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import paired_comparison.setting_models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parameters_title', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='Название параметров'), null=True, size=None)),
                ('url', models.CharField(default=paired_comparison.setting_models.create_url, max_length=50, verbose_name='Адрес для просмотра результатов')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='upload_file', verbose_name='Файл')),
                ('result_fin', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('first_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_id', models.IntegerField()),
                ('title', models.TextField(verbose_name='Название объекта')),
                ('parameters', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='Параметр'), size=None)),
                ('number_comparisons', models.IntegerField(default=0)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paired_comparison.comparisons')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('final', models.DateTimeField(null=True)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paired_comparison.comparisons')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paired_comparison.users')),
            ],
        ),
        migrations.AddField(
            model_name='comparisons',
            name='users',
            field=models.ManyToManyField(through='paired_comparison.ComparisonUser', to='paired_comparison.Users'),
        ),
    ]
